### ISSUE TITLE
Rust benchmark results

### ISSUE THREAD

**Issue by rockwotj** [hashrocket/websocket-shootout#18]
Is it possible to run the rust code on the same machines to see what the compared results are?

**Comment by jackc** [comment]
I plan on it. I still need to test the new multithreaded Rust implementation and merge that (assuming all works). We are also working on merging several other new implementations.

It takes a fair amount of time to rerun the entire benchmark. I hope to get to rerun it for Rust and all the other new implementations within a week or so.

**Comment by rockwotj** [comment]
Awesome thanks! Please close this when you get a change, no rush, great work here btw :smile:

**Comment by jackc** [comment]
Finally got a chance to run all the benchmarks with all the new implementations. The new test is a little more demanding so absolute numbers are lower. Current leader is Node with uws at 26k (though that was a single run that I was unable to reproduce...) Best reproducible is Haskell at 25k. The best Rust run came in at 20k clients. 

See results/result-02.md for the raw data.
