### ISSUE TITLE
Document build dependencies

### ISSUE THREAD

**Issue by allanlewis** [hashrocket/websocket-shootout#25]
I'm trying to build the benchmark tool on Fedora 23, but I'm struggling to satisfy the dependencies; I'm using Go 1.5.4. Initially I got these errors:

``` sh
$ make bin/websocket-bench                                                                                              
cd go/src/hashrocket/websocket-bench && go install
main.go:11:2: cannot find package "github.com/spf13/cobra" in any of:
    /usr/lib/golang/src/github.com/spf13/cobra (from $GOROOT)
    ($GOPATH not set)
action_cable_server_adapter.go:6:2: cannot find package "golang.org/x/net/websocket" in any of:
    /usr/lib/golang/src/golang.org/x/net/websocket (from $GOROOT)
    ($GOPATH not set)
make: *** [Makefile:16: /home/alewis/git/websocket-shootout/go/bin/websocket-bench] Error 1
```

I then installed the following packages and their dependencies from the Fedora repos:

``` sh
golang-golangorg-net-devel-0-0.33.git4d38db7.fc23.noarch
golang-github-spf13-cobra-devel-0-0.16.git8e91712.fc23.noarch
```

After this, `make` threw exactly the same errors. I set my `GOPATH` to `./go` and then got this error:

``` sh
$ make bin/websocket-bench 
cd go/src/hashrocket/websocket-bench && go install
main.go:11:2: no buildable Go source files in /home/alewis/git/websocket-shootout/go/src/github.com/spf13/cobra
action_cable_server_adapter.go:6:2: cannot find package "golang.org/x/net/websocket" in any of:
    /usr/lib/golang/src/golang.org/x/net/websocket (from $GOROOT)
    /home/alewis/git/websocket-shootout/go/src/golang.org/x/net/websocket (from $GOPATH)
make: *** [Makefile:16: /home/alewis/git/websocket-shootout/go/bin/websocket-bench] Error 1
```

If it isn't obvious already, I have little experience with building Go applications: a few instructions in the Readme would be really helpful.

**Comment by jackc** [comment]
The missing piece was git submodule initialization. I added it to the README.md.

On another note, I think the everything should work with Go 1.5.4, but current release is 1.7.0 and there have been significant performance improvements since 1.5.4. I'd recommend upgrading if your going to do any benchmarking.

**Comment by allanlewis** [comment]
Thanks, @jackc - all working now :+1:
