### ISSUE TITLE
cpp uWebSockets impl is single threaded

### ISSUE THREAD

**Issue by moshen** [hashrocket/websocket-shootout#33]
The [uWebSockets server implementation](https://github.com/hashrocket/websocket-shootout/blob/465fb62091250d08c9237a20bbdefe5a93828a6b/cpp/uwebsockets/src/server.cpp) is single threaded.  [Please take a look at the uWebSockets multi-threaded example](https://github.com/uWebSockets/uWebSockets/blob/059995b7745b0b3dc9b25916bdbd3265a48dc028/examples/multithreaded_echo.cpp).

**Comment by jackc** [comment]
Unfortunately, it's not so simple as the example. The worker servers need to communicate, and the documentation does not declare what is thread-safe. However, I got an answer from the author in https://github.com/uWebSockets/uWebSockets/issues/244 and was able to implement an (ugly) multi-threaded implementation.

That said, it doesn't seem to make much difference for a simple broadcast benchmark. I think it is hitting the a OS/networking stack/network ceiling.
