### ISSUE TITLE
Questions about JavaScript in Round 2

### ISSUE THREAD

**Issue by kazzkiq** [hashrocket/websocket-shootout#52]
I've got some questions related to JavaScript/uws performance in [Round 2](https://github.com/hashrocket/websocket-shootout/blob/master/results/round-02.md) benchmark.

1. At the [single-thread uws benchmark](https://github.com/hashrocket/websocket-shootout/blob/master/results/round-02.md#javascript--node--uws), it is said that:

> "Note - was only able to get near these results once."

And why is that? There were any errors in other runs? The results went too differently? If so, what was the average perf numbers?

2. At the [clustered uws benchmark](https://github.com/hashrocket/websocket-shootout/blob/master/results/round-02.md#javascript--node--uws---clustered) the results obtained were less than half of those in the non-clustered benchmark (single-thread). Since Node generally receives a huge pump on performance when running in cluster mode, do you guys have any guess as to why in this case the result was the opposite (clustered running half the speed of non-clustered)?

**Comment by lpinca** [comment]
@kazzkiq see https://github.com/hashrocket/websocket-shootout/commit/4c3d320a824c7f4101b1b3317566b1af654ab0b6#commitcomment-19444168.

**Comment by kazzkiq** [comment]
Perfect. My two questions got answered in that comment. Thanks!

**Comment by kazzkiq** [comment]
So to put things clear:

Using uws, Node.js seems to run at almost the same speed as its C++ counterpart. Which means that, using uws, it gets the second place in terms of performance, while still having the lowest number of lines of code to get up and running.

Using other packages and running in cluster mode, while slower than uws, still puts Node.js performance above the 39% described in the [blog post](https://hashrocket.com/blog/posts/websocket-shootout).

So I believe those were pretty interesting results, and perhaps other languages also have other tricks up their sleeves that could be used to optimize their performance. So maybe it would be interesting to do a **Websocket Shootout 2.0** with improved code and updated results? 🏇

**Comment by lpinca** [comment]
> Using uws, Node.js seems to run at almost the same speed as its C++ counterpart.

I would say that it's not Node.js that runs as fast as C++ it's uws which doesn't use Node.js. uws completely skips the whole Node.js stack. It only uses it to get a connection. Then the connection is transferred to the internal uws C++ server. Once transferred the Node.js [`net.Socket`](https://nodejs.org/api/net.html#net_class_net_socket) is destroyed. All is gone after that (no streams, no eventemitters, etc).
