### ISSUE TITLE
JVM settings for Clojure

### ISSUE THREAD

**Issue by puredanger** [hashrocket/websocket-shootout#6]
I'm not sure what version of the JVM or JVM settings are being used for Clojure, but they will have some impact on performance. I would highly recommend using the latest version of Java 8 and running with at least the following JVM options:

-server                           # probably will be auto-selected, but doesn't hurt to be specific
-XX:+AggressiveOpts   # enables optimizations that will be default in the next major JDK version

Those are pretty much guaranteed to be not worse and likely better than not using them. Other settings that might help are those around heap size and GC but that's harder to analyze without knowledge of the runtime profile (and knowing whether its memory constrained).

**Comment by jackc** [comment]
Done along with a few other changes in cad8f3bd38e005bca6a19095e5592af29f022a58 -- thanks to @jcf.
